name: Test Action
on: push
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- uses: DickLundblad/linkedIn-learning-challenge-create-custom-action@v0.2.4-alpha
      - uses: DickLundblad/linkedIn-learning-challenge-create-custom-action@main
        id: custom-action  # Added an ID to reference it later
        with:
          json_file: 'data.json' 
      - name: Print Environment Variables
        run: env | grep 'name' 
      - name: Print all environment variables
        run: env
        
