name: Test Action
on: push
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DickLundblad/linkedIn-learning-challenge-create-custom-action@v0.2.4-alpha
        id: custom-action  # Added an ID to reference it later
        with:
          json_file: 'data.json'
          
      - run: | 
          echo: "Value of variable name: $name"
          echo ${{ steps.custom-action.outputs.name }}
          echo "Loaded value: ${{ steps.custom-action.outputs.name }}"
