name: Test Action
on: push
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- uses: DickLundblad/linkedIn-learning-challenge-create-custom-action@v0.2.4-alpha
      - uses: DickLundblad/linkedIn-learning-challenge-create-custom-action@vmain
        id: custom-action  # Added an ID to reference it later
        with:
          json_file: 'data.json' 
      - name: Print Environment Variables
        run: env | grep 'name' 
      - name: Print Environment Variables components array
        run: env | grep 'components'       
      - name: Print Environment Variables testdata array
        run: env | grep 'testdata'
      - name: Print Environment Variables testdata array item
        run: env | grep 'testdata_0_name'
        
